language: csharp
solution: Edison.sln
mono:
  - latest
install:
  - nuget restore Edison.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.5" /p:DebugSymbols=False Edison.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Edison.Console.Tests/bin/Release/Edison.Console.Tests.dll ./Edison.Framework.Tests/bin/Release/Edison.Framework.Tests.dll