language: csharp

solution: Edison.sln

mono:
  - latest

install:
  - nuget restore Edison.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.5" /p:DebugSymbols=False Edison.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Edison.Console.Test/bin/Release/Edison.Console.Test.dll ./Edison.Framework.Test/bin/Release/Edison.Framework.Test.dll ./Edison.Engine.Test/bin/Release/Edison.Engine.Test.dll

addons:
  code_climate:
    repo_token: 76533cd443393459049733178706dfb46faff15c4762d959a093f9adc830bfde